name: deploy
on:
  push:
    branches: main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo ${{github.ref}}

      - name: Checkout
        uses: actions/checkout@v4

      - name: List files in the repository
        run: ls -R

      - name: Install dependencies
        run: npm install

      - name: Run build
        env:
          NODE_ENV: production
          REACT_APP_GOOGLE_CLIENT_ID: ${{ secrets.REACT_APP_GOOGLE_CLIENT_ID }}
        run: |
          unset CI
          npm run build

      - name: Show current branch
        run: git branch

      - name: Show remote branches
        run: git branch -r

      - name: check out gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: clean repository
        run: |
          cd gh-pages
          git clean -fdx

      - name: commit cleanup changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd gh-pages
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add -u  # Stage changes (if any)
          git commit -m "Clean up gh-pages after deployment" || echo "No changes to commit"
          git push
